### ISSUE TITLE
Support IntelliJ 2021.3

### ISSUE THREAD

**Issue by busches** [cedricziel/idea-concourse#24]
I know support for 2021.2 was just added and released, but 2021.3 came out today.

```
Plugin 'Concourse CI Support' (version '0.0.11') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-213.5744.223
```

Is there a way to support future versions out of the box or does IntelliJ have that many breaking changes each release?

**Comment by cedricziel** [comment]
With other plugins I made better experience providing version by version support, which makes it easier for me to also do deprecations and stuff.

I'll update as soon as I can - thanks for opening the issue!

**Comment by cedricziel** [comment]
Release was triggered, it's now on Jetbrains to approve it :)
