### ISSUE TITLE
Support for 2022.2.*

### ISSUE THREAD

**Issue by lorand-plensys** [cedricziel/idea-concourse#56]
Please add support for 2022.2.*

**Comment by lorands** [comment]
Created PR for this.
https://github.com/cedricziel/idea-concourse/pull/59

**Comment by jakul** [comment]
@cedricziel I'd love to use this plugin, but it's not compatible with the current version of PyCharm. Could you look at cutting a new release which supports 2022.2.* please? @lorands has raised a PR which could be all that's needed.

**Comment by cedricziel** [comment]
Fixed with v0.0.14 - thank you for your contributions!
